### ISSUE TITLE
获取 bmob-sdk-3.5.1.aar 失败

### ISSUE THREAD

**Issue by okgays** [bmob/bmob-android-sdk-demo#1]
通过这个maven地址获取失败，maven { url "https://raw.github.com/bmob/bmob-android-sdk/master" }，请问是不是这个链接失效了

**Comment by Ni2014** [comment]
我这边没翻墙也是可以的，你在gradle文件中compile了吗，如果你那边的网络一直不行，只能先试下本地依赖。

**Comment by okgays** [comment]
换了网络，可以了。谢谢！
